const RECEIVE_COLORS = 'RECEIVE_COLORS';
const ADD_COLOR = 'ADD_COLOR';
const REMOVE_COLOR = 'REMOVE_COLOR'
const VALIDATION_ERROR = 'VALIDATION_ERROR';
const VALIDATION_SUCCESS = 'VALIDATION_SUCCESS';
const SERVER_ERROR_GET = 'SERVER_ERROR_GET';
const SERVER_ERROR_POST = 'SERVER_ERROR_POST';
const SERVER_ERROR_DELETE ='SERVER_ERROR_DELETE';

export {
    RECEIVE_COLORS,
    ADD_COLOR,
    REMOVE_COLOR,
    VALIDATION_ERROR,
    VALIDATION_SUCCESS,
    SERVER_ERROR_GET,
    SERVER_ERROR_POST,
    SERVER_ERROR_DELETE
}
