const RECEIVE_COLORS = 'RECEIVE_COLORS';
const ADD_COLOR = 'ADD_COLOR';
const REMOVE_COLOR = 'REMOVE_COLOR'
const VALIDATION_ERROR = 'VALIDATION_ERROR';
const VALIDATION_SUCCESS = 'VALIDATION_SUCCESS';

export {
    RECEIVE_COLORS,
    ADD_COLOR,
    REMOVE_COLOR,
    VALIDATION_ERROR,
    VALIDATION_SUCCESS
}
